### ISSUE TITLE
complete high-level abstraction layer

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#111]
Right now Neon offers a _hint_ of a high-level abstraction layer with the `declare_types!` class macro, but regular functions still have to be defined at a lower level of abstraction, and even the class macro sometimes drops the programmer down unnecessarily to the low layer.

We should complete the high-level abstraction layer to let developers define all the kinds of JS abstractions possible with convenient, DRY syntax. This will make Neon easier to learn and much more pleasant to use:

``` rust
declare_functions! {
    function is_greeter(x: JsValue) : bool {
        Ok(x.is_a::<JsGreeter>())
    }

    function call_thunk(f: JsFunction) {
        let scope = self.scope;
        let args: Vec<Handle<JsValue>> = vec![];
        try!(f.call(scope, JsUndefined::new(), args));
        Ok(())
    }
}
```

It'll take a few steps to get there. Here's a rough game plan:
- [ ] #112: Initial `declare_functions!` macro with mandatory `JsValue` return type annotation
- [ ] #113: Migrate the `declare_types!` macro to have matching syntax
- [ ] #114: Customizable return types in class and function macros
- [ ] #115: Handle's messiah
- [ ] #116: Helix-style coercion protocol

**Comment by mfpiccolo** [comment]
Yes @dherman 🎉

**Comment by dherman** [comment]
A sketch of an even more complete end-to-end UX: https://gist.github.com/dherman/f4131507f070ad049bf557dc0c75de0a

**Comment by dherman** [comment]
This is pretty open-ended so I'm closing. In the Neon 2.0 time frame we'll still explore some big design improvements in this space.
