### ISSUE TITLE
Checklist: crash safety

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#144]
These are the major remaining pieces for achieving crash safety:

- [ ] #52: Neon needs to be aware of the engine's throwing state
- [x] #143: need to convert unwinding panics to JS exceptions
- [ ] #193: exception (panic) safety

Once we finish these, we should be able to describe Neon as safe without qualifiers -- i.e., at that point, any crashes are just bugs that need to be fixed. In a sense, that's all these are, too. But they're pretty major so they need to be implemented before Neon can start making stronger safety promises.

**Comment by kjvalencik** [comment]
This has been resolved in the Node-API backend. There is a breaking change also being considered that would return `JsResult` everywhere instead of panicking on an exception.
