### ISSUE TITLE
Quest: N-API Support

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#444]
Prepare, once and future Neon contributors, for our noblest quest yet!

![Pippin: Great! Where are we going?](https://media.giphy.com/media/w5x8GjarjZADm/giphy.gif)

We are going to port Neon to Node's new [N-API](https://nodejs.org/api/n-api.html)!

![Pippin: Huh?](https://media.giphy.com/media/mBWi28isKkAG4/giphy.gif)

I'll explain. N-API brings to Neon the promise of a stable, backwards-compatible ABI—binary compatibility across all future versions of Node.

This is a big deal.

Portability across Node versions means **Neon will finally be practical for publishing libraries, not just apps:** a few prebuilt binaries should be sufficient for all downstream customers to use your native library without ever knowing the difference.

![Pippin: Oh, I get it!](https://media0.giphy.com/media/zTzZsbf0XapZS/giphy.gif)

The stuff of legend, no?

# Our Quest

## Step 1. Create the feature flag

- [x] Create a [cargo feature flag](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section) to allow us to concurrently maintain the main Neon codebase along with the experimental N-API support in the same master branch. ([Merged!](https://github.com/neon-bindings/neon/pull/440))
- [x] Set up a test suite specifically for the N-API backend so each task can easily include adding tests (#449)

## Step 2. Implement the port

- [x] **Module contexts and initialization:** Implement the `neon::context::ModuleContext` type and pass it to the module initialization function inside the `register_module!` macro defined in `/src/lib.rs`. The context struct will likely need to encapsulate the underlying `napi_env` and `napi_value` as private fields. This can be implemented before we implement functions, with an unimplemented `export_function()` method for now.
- [x] **Functions:** This is probably one of the subtler tasks. See the implementation of `neon::types::JsFunction::new()`. The Rust callback can be stored as the extra `void*` data passed to `napi_create_function`.
- [x] **Function arguments:** Implement `CallContext::len()` and `CallContext::argument()`.
- [x] **Function returns:** Implement function return values.
- [x] **`this`:** Implement `CallContext::this()`.
- [x] **Call kinds:** Implement `CallContext::kind()`.
- [x] **Function exports:** Once we have module contexts and functions implemented, we can implement the `ModuleContext::export_function()` shorthand method.
- [x] **Objects:** See `neon::types::JsObject::new()` and the `neon::object::Object` methods.
- [x] **Arrays:** See `neon::types::JsArray`.
- [x] **ArrayBuffers and Buffers:** See `neon::types::binary` and the N-API functions for working with binary data, such as `napi_create_arraybuffer`, `napi_create_buffer`, etc.
- [x] **Uninitialized and null:** These should be pretty bite-sized. See `neon::types::JsUndefined` and `neon::types::JsNull`. @goto-bus-stop 
- [x] **Booleans:** See `neon::types::JsBoolean`. @goto-bus-stop 
- [x] **Numbers:** See `neon::types::JsNumber`.
- [x] **Strings:** See `neon::types::JsString`. We'll need to explore what binary string representations can be used between the NAN vs N-API runtimes for constructing JS strings.
- [x] ~**Classes:** This will require us to figure out how to do unique branding with N-API, but I believe `napi_define_class` supports this. (Here is one [pure C example](https://github.com/nodejs/node-addon-examples/blob/master/thread_safe_function_round_trip/node-api/round_trip.c#L316-L322) we can look to for inspiration.)~ <== not needed for functional completeness; see #596
- [x] **Errors:** See `neon::types::error`. We'll need to explore how N-API does throwing and catching errors. - @anshulrgoyal 🔒
- [x] **Conversions:** See the uses of `neon_runtime::convert::*` and the `napi_coerce_*` functions.
- [x] **Scopes:** Luckily, the N-API HandleScope mechanim matches V8's mechanism very closely. See `neon::context` and the uses of various HandleScope internal types.
- [x] **Tag checks:** See uses of `neon_runtime::tag::*`.
- [x] ~**Task scheduling:** See `neon::task` and `neon::context::TaskContext`, and the N-API "simply asynchronous operations" API, which uses the same underlying libuv thread pool as Neon's current backend, but with N-API's stable ABI.~ <== not needed for functional completeness; see #596
- [x] ~**Thread-safe callbacks:** This can be implemented for N-API once we've merged an implementation for [RFC 25](https://github.com/neon-bindings/rfcs/blob/master/text/0025-event-handler.md), using `napi_make_callback`.~ <== not needed for functional completeness; see #596
- [x] **Windows Support:** Windows requires linking against `node.lib` and `win_delay_load_hook`. Create a custom build script to link these on windows.

We have just a couple remaining items to finish up:

- [x] Equality comparison of handles - see #666
- [x] `JsBuffer::uninitialized` - see #664

## Step 3. Deprecate the legacy runtime

Once we finish the complete port, we can switch the default feature flags to use the new runtime and publish a new 0.x minor version. Eventually after a few releases we can remove the old runtime completely.

# How to Contribute

## Building N-API-based projects

To experiment with the N-API runtime or do manual testing, you can create a Neon project that uses the right feature flags. To try it out, you can run:
```
neon new --no-default-features --features=napi-latest --neon=path/to/neon my-project
```
where `path/to/neon` is the path on your local filesystem to a local clone of the Neon repo.

### Manual Steps

The output of `neon new` executed above will produce a project that fails to build. When using the `neon` backend, either `neon-build` should be used with a simple `cargo build` or `neon-cli` should be used and `neon-build` should be removed. If both are used, the project will fail to build.

There is an RFC (https://github.com/neon-bindings/rfcs/pull/36) to replace `neon new` which will correctly generate a project. The simplest change is to edit `native/Cargo.toml`:

* Remove the `neon-build` dependency
* Remove `build = "build.rs"`
* delete `native/build.rs`

**Note:** If you create a Neon project nested inside the directory tree of a clone of the Neon repo, you'll need to add the line
```
[workspace]
```
to your Neon project's `native/Cargo.toml` manifest in order to build the project.

## Adding an N-API primitive

To add an N-API primitive, you should implement it in pure Rust (using `unsafe` as necessary, but only as necessary!) in `crates/neon-runtime/napi`, and call out to the N-API backend exposed through `nodejs-sys`.

When the Neon runtime needs to pass around a data structure, you can make two different definitions of the type, separated by testing the feature flag with `#[cfg(feature = "...")]`. You may sometimes need to refactor the types in the Neon runtime to accommodate differences between the legacy and N-API runtimes.

## Adding a test

The `test/napi` directory is the space for adding N-API acceptance tests. You can add native Rust logic to `test/napi/native/src` and JS logic to `test/napi/lib`. You can get examples of existing acceptance tests in our existing backend in `test/dynamic`, which has the same structure.

# Will You Join Us?

As you can see, the quest ahead of us will be no small feat!

![Pippin: Anyway you'll need people of intelligence on this... thing](https://media0.giphy.com/media/mppSUXCZPfXVK/source.gif)

Indeed, but fear not: we're here to help you if you get stuck. And many of these tasks can be a great way to get started with contributing to Neon and even learning Rust.

Claim one of the tasks today by leaving a comment below or pinging @dherman or @kjvalencik on Slack!

![Pippin: I'm getting one](http://giphygifs.s3.amazonaws.com/media/10JCmN6NYFkL6w/200.gif)

**Comment by ciscojeremy** [comment]
I'm interested.

**Comment by dherman** [comment]
@ciscojeremy Awesome! Are you on the community Slack? @kjvalencik is just now working on some refactoring so you might want to sync up with a chat.

**Comment by ciscojeremy** [comment]
Nope, I'm not a the community slack. How do I join?

**Comment by kjvalencik** [comment]
The [Rust Bindings community Slack](https://rust-bindings.slack.com) is open to all; use [the Slackin app](https://rust-bindings-slackin.herokuapp.com) to receive an invitation.

**Comment by Brooooooklyn** [comment]
Maybe this repo could save your time. https://github.com/Brooooooklyn/napi-rs

**Comment by kjvalencik** [comment]
:wave: I'm working on `ModuleContext `and initialization.

**Comment by jrop** [comment]
This is the best dev-related news today! (came from [Twitter](https://twitter.com/RustNeon/status/1187221064947908608))

**Comment by dio** [comment]
Wow. I’m so excited! I hope I can contribute something! _joining the community slack_

**Comment by qwelias** [comment]
I'd like to learn rust, but I have no experience yet, would like to contribute and have lots of experience with node tho. So if you think a total rust noob can be trusted with a certain task -- hit me :)

**Comment by kjvalencik** [comment]
@qwelias definitely! There will be some beginner friendly Rust tasks and likely some pure javascript as well. And, of course, testing and vetting of ideas are always needed!

**Comment by goto-bus-stop** [comment]
I'm looking at undefined/null for a start! Possibly bools too if they are as similar as I suspect, so all the global singleton values could be done in one go.

**Comment by timsuchanek** [comment]
What are some of the next possible steps here?

**Comment by goto-bus-stop** [comment]
i was planning on working on either objects or functions this Friday

**Comment by goto-bus-stop** [comment]
ah i thought numbers got in together with bools but i had them in a separate branch: https://github.com/neon-bindings/neon/pull/492

started working on objects and as i was writing a test case, i wanted to use tag checks like `val.is_a::<JsNumber>()` as well, so that's where i'm looking. the tag checks need lots of boring mechanical changes to thread the `Context` value through a dozen layers :upside_down_face:

**Comment by timsuchanek** [comment]
Nice! So it sounds like a first prototype-ish version would already be usable quite soon?

**Comment by goto-bus-stop** [comment]
I also started working on function calls (from JS into Rust for now) so parts of the existing test suite can be run on n-api.

@timsuchanek once both objects and function calls are in, some _very limited_ use cases would be possible. I expect many real-world cases would want the Class stuff from Neon so you can pass Rust structs between JS and Rust, so they can live for longer than a single call, so that would probably come next

**Comment by goto-bus-stop** [comment]
Functions, function arguments, and function return values can be checked off now that #507 is merged :tada: 

I would like to look at ArrayBuffers support next, since #507 already ported a few of the buffer tests that are currently being skipped.

**Comment by goto-bus-stop** [comment]
Looking into getting the N-API runtime going on Windows today!

**Comment by dherman** [comment]
We're almost there! I've struck out the items that are not needed for functional completeness and noted them in the new #596 issue for the deprecation plan. All that's left is to review the implementation of `ComputeContext` and `ExecuteContext` to make sure they properly create nested scopes, and we'll be able to close this issue!

**Comment by wspl** [comment]
Would neon n-api support Electron without electron-rebuild or electron-build-env?

**Comment by kjvalencik** [comment]
@wspl Correct, they would not be needed. There would be a minimum n-api version that we might need to provide to neon with alternate means if we use APIs that aren't in the Electron node version yet, but we could probably do that with feature flags.

**Comment by dherman** [comment]
With the merging of #664 and #666, the last two items on the list are done, and **the quest is officially complete!** Congratulations and a _huge_ thank you to everyone who contributed to making it happen!

![200-5](https://user-images.githubusercontent.com/307871/104491780-91ccdc00-5587-11eb-967b-f8c223a366c7.gif)
